# Tomcat
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 8081

# mysql数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3307/ssm_cluster_db?useSSL=false&characterEncoding=utf8
        username: root
        password: root
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/views/

logging:
  level:
    com.stargis.epr: debug

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

